### ISSUE TITLE
automate events management

### ISSUE THREAD

**Issue by madhums** [xrnl/extinction-rebellion-nl#32]
Right now events are copied to Meetup from Facebook (this is a lot of manual work) and then imported from meetup via a plugin.

Major issues with this approach, which makes it less scalable.
1. A lot of manual work, one or two people have to volunteer and do this every week. Takes a good few hours.
2. When an event gets updated on Facebook, then it needs to be updated on meetup and then also on the website. It's hard to keep an overview of this.
2. When an event gets cancelled, then some one has to cancel it on meetup and also remove it on the website. Hard to keep on overview of this.

Why are we not importing events from Facebook?
1. Facebook needs `page_access_token` and it's impossible to get this. One must register a business and send documents. We didn't explore this approach further.
2. Using Facebook webhooks is also difficult as it needs `page_access_token`
3. Using Facebook events API - it's only possible to read a single event, they've disabled creating of events. Plus you need `page_access_token`

We do need to support a wider audience as not everyone uses Facebook. Hence we use meetup and website.

How can we improve this?

**Comment by decentral1se** [comment]
FYI for anyone coming along here, there is a further discussion happening on the NL discourse where a solution might appear sooner than over here due to higher visibility.

**Comment by SamLubbers** [comment]
This issue is being resolved internally by the tech team of XR NL.
