### ISSUE TITLE
Align social buttons in the mobile navigation menu

### ISSUE THREAD

**Issue by franei** [xrnl/extinction-rebellion-nl#44]
Inside the mobile dropdown navigation the social & donate buttons are out of alignment with the rest of the menu.
It's quickly fixed in `header.php` by moving the `<ul>` with the buttons out of the `<div>` that contains the language switcher. 

Before/after screenshots are below. The desktop-width regular navbar stays unchanged by this.
If people agree I can make this a pull request.

# Before:
<img width="1156" alt="Before-desktop" src="https://user-images.githubusercontent.com/25393215/74272344-c187ba00-4d0e-11ea-9bf6-b6b72f275061.png">
<img width="341" alt="Before-phone" src="https://user-images.githubusercontent.com/25393215/74272353-c3517d80-4d0e-11ea-9c2d-061e64ac10ab.png">
<img width="551" alt="Before-tablet" src="https://user-images.githubusercontent.com/25393215/74272355-c3ea1400-4d0e-11ea-9995-0cd09bdf0296.png">

# After:
<img width="1150" alt="After-desktop" src="https://user-images.githubusercontent.com/25393215/74272391-d2383000-4d0e-11ea-8b5b-473a7a9b0b63.png">
<img width="343" alt="After-phone" src="https://user-images.githubusercontent.com/25393215/74272393-d3695d00-4d0e-11ea-8e56-edc7ca52dcfc.png">
<img width="544" alt="After-tablet" src="https://user-images.githubusercontent.com/25393215/74272394-d401f380-4d0e-11ea-8411-0798b83586c5.png">

# Unchanged:
<img width="1219" alt="Wide-unchanged" src="https://user-images.githubusercontent.com/25393215/74272426-e1b77900-4d0e-11ea-9783-b4e940d2a706.png">

**Comment by madhums** [comment]
If this is a really small and simple change, go ahead!
