### ISSUE TITLE
Error accessing images in local instance

### ISSUE THREAD

**Issue by SamLubbers** [xrnl/extinction-rebellion-nl#56]
Currently, when media files [are synced](https://github.com/xrnl/extinction-rebellion-nl/blob/master/docs/sync-production-data.md) from the production site, they are locally accessed through `https`. Because the local site is running on `http` and not `https` images are not loaded and you get the error `SSL received a record that exceeded the maximum permissible length.`

**Comment by franei** [comment]
Running the local web server on `https` also solved this problem for me (but that's without using the current Docker image of course).

**Comment by SamLubbers** [comment]
haha the Docker image brings nothing but difficulties 😂 Once you have publish the instructions for running the website without docker we can close this issue.

**Comment by SamLubbers** [comment]
Closing as this issue has been registered in the internal management system, which will be used for managing issues from now on.
